config/routes.rb
Bogofy::Application.routes.draw do

  match 'dashboard', to: 'dashboard#index', as: 'dashboard'  
  get "dashboard/index"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'  

 

  
  resources :users do 
    resources :lists do
      resources :items
    end
  end

  root to: 'pages#home'

  match 'take-a-tour', to: 'pages#tour', as: 'tour'
  get 'pages/tour'

  match 'sign-up', to: 'identities#new', as: 'signup'
  get 'pages/signup'

  match 'login', to: 'pages#login', as: 'login'
  get 'pages/login'
  resources :identities

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  attr_accessible :email, :name, :password_digest, :password, :password_confirmation
  
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, with: /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :list_id

  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name

  has_many :items, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid
 
  has_many :lists, dependent: :destroy

  extend FriendlyId
  friendly_id :name, use: :slugged
 
  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
  		user.provider = auth.provider
  		user.uid = auth.uid
  		user.name = auth.info.name
  		user.oauth_token = auth.credentials.oauth_token
  		user.oauth_expires_at = Time.at(auth.credentials.expires_at) unless auth.credentials.expires_at.nil?
  		user.save!
  	end
  end

  #def to_param
  #  "#{:id} - #{current_user.name}"
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def check_sign_in
  	unless user_signed_in?
  		redirect_to root_path
  	end
  end

  def user_signed_in?
  	return true if current_user
  end
  helper_method :user_signed_in?

private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController

	def new
		@identity = env['omniauth.identity']
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  

  def create
    @user = current_user
    @list = @user.lists.find(params[:list_id])
    @item = @list.items.create(params[:item])
    respond_to do |format|
      format.html { redirect_to user_list_path(@user, @list) }
      format.js
    end
  end

  #def edit
  #  @item = Item.find(params[:id])
  #end
#
  #def update
  #  @item = Item.find(params[:id])
  #  if @item.update_attributes(params[:item])
  #    redirect_to @item, :notice  => "Successfully updated item."
  #  else
  #    render :action => 'edit'
  #  end
  #end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to :back
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
  before_filter :check_sign_in

  def index
    @user = current_user
    @lists = @user.lists.all
  end

  def show
    @user = current_user
    @list = @user.lists.find(params[:id])
    @item_list = @list.items.all
  end

  def new
    @user = current_user
    @list = @user.lists.new
  end

  def create
    @user = current_user
    @list = @user.lists.create(params[:list])
    if @list.save
      redirect_to user_lists_path, :notice => "Successfully created list."
    else
      render :action => 'new'
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update_attributes(params[:list])
      redirect_to @list, :notice  => "Successfully updated list."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_url, :notice => "Successfully destroyed list."
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def tour
  end

  def signup
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = User.from_omniauth(env["omniauth.auth"])
		session[:user_id] = user.id
		redirect_to user
	end

	def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :check_sign_in

  before_filter :current_user
  
  def show
  	@user = User.find(params[:id])
  
  	@lists = List.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<div class="dashboard-header">
<div class="container-narrow">
	Logged in as <%= current_user.name %>
	<h3>Dashboard</h3>
</div>
</div>

app/views/identities/new.html.erb
<p class="login-heading">Sign Up for <span class="green-text">Bogo</span>fy</p>
<div class="signup-container">
	<div class="signup-form">


		

		<%= link_to (image_tag "fb.png", size: "325x68", class: "fb-image"), "/auth/facebook" %>

		<h4 class="or">- OR -</h4>

		<h2 class="free-account">Sign up for a FREE Account</h2>

		<%= form_tag "/auth/identity/register", autocomplete: "off" do %>
				<label>Name</label>
				<%= text_field_tag :name, @identity.try(:name), class: "input-block-level" %><br>
				<label>Email</label>
				<%= text_field_tag :email, @identity.try(:email), class: "input-block-level" %><br>
				<label>Password</label>
				<%=  password_field_tag :password, nil, class: "input-block-level" %><br>
				<label>Confirm Password</label>
				<%= password_field_tag :password_confirmation, nil, class: "input-block-level" %><br>
				<br>
				<%= submit_tag "    Sign Up    ", class: "btn btn-custom btn-large signup-btn" %> 

			<% end %>
	</div>
</div>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :list_id %><br />
    <%= f.number_field :list_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/items/create.js.erb
$('#item-list').append('<%= j render 'item_list' %>');

app/views/items/edit.html.erb
<% title "Edit Item" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @item %> |
  <%= link_to "View All", items_path %>
</p>

app/views/items/index.html.erb
<% title "Items" %>

<table>
  <tr>
    <th>Name</th>
    <th>List</th>
  </tr>
  <% for item in @items %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.list_id %></td>
      <td><%= link_to "Show", item %></td>
      <td><%= link_to "Edit", edit_item_path(item) %></td>
      <td><%= link_to "Destroy", item, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Item", new_item_path %></p>

app/views/items/new.html.erb
<% title "New Item" %>

<%= render 'form' %>

<p><%= link_to "Back to List", items_path %></p>

app/views/items/show.html.erb
<% title "Item" %>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>
<p>
  <strong>List:</strong>
  <%= @item.list_id %>
</p>

<p>
  <%= link_to "Edit", edit_item_path(@item) %> |
  <%= link_to "Destroy", @item, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", items_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bogofy</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Sanchez' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for([@user, @list]) do |f| %>
  
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/lists/_item.html.erb
<%= item.name %>

app/views/lists/_item_list.html.erb
<% @item_list.each do |item| %>
		<%= item.name %><br>
	<% end %>

app/views/lists/create.js.erb
$('#item-list').append('<%= j render 'item_list' %>');

app/views/lists/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @list %> |
  <%= link_to "View All", lists_path %>
</p>

app/views/lists/index.html.erb
<%= render "partials/dashboard_header" %>
<div class="container-narrow">
	<h2>My Lists</h2>

<% for list in @lists %>
  <p><%= link_to list.name, user_list_path(@user, list) %></p>
<% end %>

<%= link_to "Add List", new_user_list_path %>

</div>

app/views/lists/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", user_lists_path %></p>

app/views/lists/show.html.erb
<%= render "partials/dashboard_header" %>
<div class="container-narrow">
<h3><%= @list.name %></h3>

<%= form_for [@user, @list, @list.items.build], html: { class: "form-inline" } do |f| %>
	<%= f.text_field :name, placeholder: "Add an item..." %>
	<%= f.submit "Add Item", class: "btn" %>
<% end %>

<div id="item-list">
	<% if @item_list.present? %>
		<%= render 'item_list' %>
	<% end %>
</div>
</div>

app/views/pages/home.html.erb
<!-- IF USER IS LOGGED IN -->

<% if user_signed_in? %>
<div class="dashboard-header-container">
	<div class="container-narrow">
		<p>Logged in as <%= current_user.name %></p>
	</div>
</div>
<h1>Someone is signed in!</h1>

<!-- IF USER IS NOT LOGGED IN -->

<% else %>
<%= render 'partials/header' %>
<div class="slider-container">
	<div class="container-narrow">
		<div class="row-fluid">
			<div class="span6">
				<div class="hm-text-container">
					<p class="welcome">Welcome to <span class="green-text">Bogo</span>fy</p>
					<p class="welcome-sub-text">The online app for couponers that allows you to track your savings, create shopping lists, and connect with other couponers, all in one place.</p>
					<br>
					<%= link_to "Take a Tour", '#', class: "btn btn-large btn-custom" %>
				</div>
			</div>
			<div class="span6">
				<div class="img-container">
					<%= image_tag "laptop.png" %>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container-narrow">
	<div class="hm-bottom">
	<blockquote>
		<div class="row-fluid">
			<div class="span9">
				<p class="blockquote-large">Get started now by signing up for a FREE account!</p>
				<p class="blockquote-small">Sign up with facebook and connect with other members to share tips and deals.</p>
			</div>
			<div class="span3 pad10">
				<%= link_to "Signup Now", signup_path, class: "btn btn-large pull-right btn-custom" %>
			</div>
	</blockquote>
	<div class="row-fluid">
		<div class="span3">
			<p class="subhead">Create Grocery Lists</p>
			<p>Lorem ipsum dolor sit amet, ipsum homero dissentiunt mei et, ex consul maiorum sed. Adhuc mucius platonem in sit. Te honestatis liberavisse nec. Id duo nominavi eligendi, eu choro iudico munere mei.</p>
			<%= link_to "More Info", "#" %>
		</div>
		<div class="span3">
			<p class="subhead">Track Transactions</p>
			<p>Lorem ipsum dolor sit amet, ipsum homero dissentiunt mei et, ex consul maiorum sed. Adhuc mucius platonem in sit. Te honestatis liberavisse nec. Id duo nominavi eligendi, eu choro iudico munere mei.</p>
			<%= link_to "More Info", "#" %>
		</div>
		<div class="span3">
			<p class="subhead">Organize Links</p>
			<p>Lorem ipsum dolor sit amet, ipsum homero dissentiunt mei et, ex consul maiorum sed. Adhuc mucius platonem in sit. Te honestatis liberavisse nec. Id duo nominavi eligendi, eu choro iudico munere mei.</p>
			<%= link_to "More Info", "#" %>
		</div>
		<div class="span3">
			<p class="subhead">Get Social</p>
			<p>Lorem ipsum dolor sit amet, ipsum homero dissentiunt mei et, ex consul maiorum sed. Adhuc mucius platonem in sit. Te honestatis liberavisse nec. Id duo nominavi eligendi, eu choro iudico munere mei.</p>
			<%= link_to "More Info", "#" %>
		</div>
	</div>
	</div>
</div>
<%= render 'partials/footer' %>
<%= render 'partials/subfooter' %>
<% end %>

app/views/pages/login.html.erb
<p class="login-heading"><span class="green-text">Bogo</span><span class="grey-text">fy</span></p>
<div class="signup-container">
	<div class="signup-form">
		<%= form_tag "auth/identity/callback", autocomplete: "off" do %>
		<label>Email</label>
		<%= text_field_tag :auth_key, nil, class: "input-block-level" %><br>
		<label>Password</label>
		<%= password_field_tag :password, nil, class: "input-block-level" %><br>
			

		<!-- Add Remember Me Functionality -->


		<label class="checkbox">
    <input type="checkbox"> Remember me | <%= link_to "Login using Facebook", "/auth/facebook", class: "facebook-link" %>
    </label>
		<br>
		<%= submit_tag "    Login    ", class: "btn btn-custom" %>

		<% end %>
	
	
	</div>
</div>

	<p class="form-links">
		<%= link_to "Home", root_path %> |
		<%= link_to "Privacy Policy", '#' %> |
		<%= link_to "Terms & Conditions", '#' %> |
		<%= link_to "Contact", '#' %> |
		<%= link_to "Sign Up", '#' %>
	</p>
	<p class="form-copyright">Copyright &copy; <%= Time.now.strftime("%Y") %> WebDSquared</p>

app/views/pages/signup.html.erb
<%= render 'partials/header' %>

<div class="signin-pg">
	<div class="container-narrow">
		<div class="signin-container">
			<p class="signin-heading">Sign Up for <span class="green-text">Bogo</span>fy</p>
			
			<%= form_tag 


		</div>	
	</div>
</div>

<%= render 'partials/footer' %>
<%= render 'partials/subfooter' %>

app/views/pages/tour.html.erb
<%= render 'partials/header' %>
<h1>Tour of the App</h1>

app/views/partials/_dashboard_header.html.erb
<div class="dashboard-header-container">
	<div class="container-narrow">
		<div class="row-fluid">
			<div class="span3">
				<h3>
					<%= link_to user_path(@user) do %>
						<i class="icon-home white-background"></i>
					<% end %>
					Bogofy Dashboard
				</h3>
			</div>
			<div class="span9">
				Logged in as <%= current_user.name %>. Not you?
				<%= link_to "Signout", "/signout"  %>
			</div>
		</div>
	</div>
</div>

app/views/partials/_footer.html.erb
<div class="footer-container">
	<div class="container-narrow">
		<div class="row-fluid">
			<div class="span4">
				<p class="ftr-subhead">Bogo<span class="white-text">fy&nbsp;:</p>
				<p class="ftr-text">Lorem ipsum dolor sit amet, ipsum homero dissentiunt mei et, ex consul maiorum sed. Adhuc mucius platonem in sit. Te honestatis liberavisse nec. Id duo nominavi eligendi, eu choro iudico munere mei.</p>
			</div>
			<div class="span4"></div>
			<div class="span4"></div>
		</div>
	</div>
</div>

app/views/partials/_header.html.erb
<div class="container-narrow">
	<div class="masthead pad20">
		<div class="navbar">
    	<ul class="nav pull-right">
      	<li><%= link_to "Home", root_path %></li>
      	<li><%= link_to "Take a Tour", tour_path %></li>
    		<li><a href="#">Blog</a></li>
        <li><%= link_to "Sign Up", signup_path %></li>
        <li><%= link_to "Login", login_path %></li>
    	</ul>
    	<h3 class="green">Bogo<span class="grey-text">fy</span></h3>
  	</div>
	</div>
</div>

app/views/partials/_subfooter.html.erb
<div class="ftr-sub">
	<div class="container-narrow">
		<div class="row-fluid">
			<div class="span6">
				</p>
			</div>
			<div class="span6">
				<p>Copyright <span class="green-text">Bogo</span>fy &copy;<%= Time.now.strftime("%Y") %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<%= render "partials/dashboard_header" %>

<div class="dashboard-main">
	<div class="container-narrow">
		<div class="row-fluid">
			<div class="span5">
				<div class="user-sidebox">
					<h2>Profile</h2>
					<h2>Transactions</h2>
					<h2>Grocery Lists</h2>
					<!-- Create User Grocery Lists -->
					<% for list in @lists %>
						<%= link_to list.name, user_list_path(@user, list) %>
					<% end %>

					<h2>Links</h2>
					<h2>
				</div>
			</div>
			<div class="span7">
				<div class="activity-container">
					Activity list
					<%= link_to "User List", user_lists_path(@user) %>
				</div>
			</div>
		</div>
	</div>
</div>